name: Monthly Model Review Reminder

# Runs on the 1st of every month at 9 AM UTC
on:
  schedule:
    - cron: '0 9 1 * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  model-review-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pricing check script
        run: |
          python scripts/check_model_pricing.py > model_review_report.txt

      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('model_review_report.txt', 'utf8');

            const issueBody = `
            ## 🔄 Monthly Model Review Due

            It's time for the monthly model pricing and availability review!

            **Philosophy:** We prioritize quality improvements and are willing to pay more for significant gains.

            ### Automated Report

            \`\`\`
            ${report}
            \`\`\`

            ### Quick Start

            Run the maintenance script:
            \`\`\`bash
            python scripts/check_model_pricing.py
            \`\`\`

            ### Checklist

            - [ ] Verify pricing at provider websites
            - [ ] Update MODEL_PRICING if changed
            - [ ] Check for new models
            - [ ] Run tests: \`pytest tests/unit/test_model_choices.py -v\`
            - [ ] Review actual cost stats: \`curl http://localhost:8001/cost/stats\`
            - [ ] Update documentation if needed
            - [ ] Commit changes with updated timestamp

            ### Resources

            - [MODEL_GOVERNANCE.md](./MODEL_GOVERNANCE.md)
            - [MODEL_DECISION_MATRIX.md](./MODEL_DECISION_MATRIX.md)
            - [LLM_PROVIDER_STRATEGY.md](./LLM_PROVIDER_STRATEGY.md)

            ---
            *This issue was automatically created by the quarterly model review workflow.*
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Monthly Review] Model Pricing & Availability Check - ${new Date().toISOString().split('T')[0]}`,
              body: issueBody,
              labels: ['maintenance', 'monthly-review', 'models']
            });

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-model-review-report
          path: model_review_report.txt
          retention-days: 90
